### PR TITLE
Add support for indenting AsciiDoc lists

### PR DESCRIPTION
**Pull request by mykoza**
Commit for issue #35

### CODE REVIEW

**Comment by dkarter** [comment]
Hi @mykoza , first thank you for the PR and I apologize about the delay. The first priority for getting any PR merged would be getting tests to pass in CI. Currently they are broken for this very specific PR and I am not sure why or how to fix them. But that would be the first priority.

As for key bindings - I currently don’t want to introduce and maintain these as part of the plugin despite the ability to optionally turn them on/off. It doesn’t seem like those are idiomatic vim mappings and I’d rather expose a function and have users of the plugin create a mapping using something like `<PLUG>indent_asciidoc`. We can include instructions in the documentation section you added about how to set those up. 

Let’s fix the CI tests first and then we can figure out the rest. Thank you for your patience with this.

**Comment by dkarter** [comment]
Here are a couple of links related to <plug> mappings:

https://vim.fandom.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_3)

https://whileimautomaton.net/2008/09/27022735

**Comment by mykoza** [comment]
Hi, thanks for the reply. I'll try to make the changes you recommend.

I saw the CI test failing, but it was already present in #36. I don't know anything about Travis, but change to plugin file was so minimal that it shouldn't fail in my opinion (additionally it works locally for you and me).

The only other thing changed in that PR was updating Ruby version. Could this affect the build in some way?

**Comment by dkarter** [comment]
> The only other thing changed in that PR was updating Ruby version. Could this affect the build in some way?

I know that's coming from my initial AsciiDoc PR which you copied into here. But I don't think that it's because of Ruby, you can see that the commit prior to the Ruby version bump was failing as well. I tried to bump the Ruby version to see if that would solve the issue but it didn't. 

I'm not really sure how to move it forward, seems like it would take some time tinkering with Travis / that particular failing test and trying to get it to work, but unfortunately I don't have a ton of time right now to dedicate to this.

**Comment by mykoza** [comment]
Hi again,
Thanks for resolving #35! My question is, do You still want this feature in your plugin, because I myself am not sure. Coincidentally I picked up this matter again today. I wrote very short, standalone code, without using any part of the plugin. It's basic and without any additional features or checks.

Gist with code: https://gist.github.com/mykoza/3a2978b2fa5c1a3c3f0252cc5ed8f2ee

**Comment by dkarter** [comment]
At the moment I don't see indentation being part of the plugin (to avoid bloat and having to support that code going forward) so I think your solution of using a separate script for that is great.

**Comment by mykoza** [comment]
Ok, thanks for staying in contact. I'm closing the PR.

**Pull request closed without merging**
