### PR TITLE
Improve key mappings customization

### PR DESCRIPTION
**Pull request by wenzel-hoffman**
Closes https://github.com/dkarter/bullets.vim/issues/127

This change introduces two things:

1. `<Plug>...` mappings for easier reuse
2. `g:bullets_custom_mappings` option where you can customize all the key mappings

I added a usage example for new `g:bullets_custom_mappings` option to the README.

### CODE REVIEW

**Comment by dkarter** [comment]
This is a great addition and a long requested feature! Thank you!
One item of feedback - i'm not sure if the `g:bullets_custom_mappings` variable is necessary.. can't the user just set up their mapping `imap <cr> <Plug>(bullets-newline)` like this, without our intervention?

I'll also say we can probably deprecate the `leader` setting now that this is available.

**Comment by wenzel-hoffman** [comment]
@dkarter the user can do this but those keys are part of the `autocmd` for specific file types. If the user just do `imap` as-is it would apply for all file types. So the behavior is different. Maybe it makes sense to make it more clear in the README?

**Comment by wenzel-hoffman** [comment]
@dkarter I added a comment making this more clear why `g:bullets_custom_mappings` can give you some benefits over making plain mappings:

``` diff
commit 1519f7191f6a2aca676465321448c1b49e3cc182
Author: Viacheslav Lotsmanov <lotsmanov89@gmail.com>
Date:   Sun Sep 11 00:04:21 2022 +0300

    README: Add clarification comment for g:bullets_custom_mappings option

diff --git a/README.md b/README.md
index 2fa48a5..782b7e0 100644
--- a/README.md
+++ b/README.md
@@ -85,6 +85,10 @@ Customize key mappings:
 let g:bullets_set_mappings = 0 " disable adding default key mappings, default = 1
 
 " default = []
+" N.B. You can set these mappings as-is without using this g:bullets_custom_mappings option but it
+" will apply in this case for all file types while when using g:bullets_custom_mappings it would
+" take into account file types filter set in g:bullets_enabled_file_types, and also
+" g:bullets_enable_in_empty_buffers option.
 let g:bullets_custom_mappings = [
   \ ['imap', '<cr>', '<Plug>(bullets-newline)'],
   \ ['inoremap', '<C-cr>', '<cr>'],
```

**Comment by dkarter** [comment]
> @dkarter the user can do this but those keys are part of the `autocmd` for specific file types. If the user just do `imap` as-is it would apply for all file types. So the behavior is different. Maybe it makes sense to make it more clear in the README?

Ah I see.. yea that makes sense

**Comment by wenzel-hoffman** [comment]
@dkarter there’s something with the CI:

```
/usr/bin/bash /home/runner/work/_actions/GabrielBB/xvfb-action/v1/cleanup.sh
Killing the following xvfb processes: 2226
kill: (2226): No such process
Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

I guess you have to just rerun the pipeline.

**Comment by dkarter** [comment]
yea not sure what's up. All tests pass for me locally. Re-running the entire pipeline now 🤞🏼 .

**Comment by dkarter** [comment]
@all-contributors please add @wenzel-hoffman for code

**Comment by dkarter** [comment]
Thanks @wenzel-hoffman, I think this will be very helpful for a lot of people!

**Pull request merged**
